export const mockData = {
  // User data
  users: [
    {
      id: 1,
      full_name: "Dr. Sophea Chann",
      email: "sophea.chann@tarl.edu.kh",
      phone: "012-345-678",
      role: "admin",
      position: "Program Director",
      school_id: null,
      province_id: 1,
      district_id: 1,
      is_active: true,
      created_at: "2024-01-01T00:00:00Z",
      updated_at: "2024-01-01T00:00:00Z",
    },
    {
      id: 2,
      full_name: "Ms. Maly Sok",
      email: "maly.sok@tarl.edu.kh",
      phone: "012-456-789",
      role: "teacher",
      position: "Senior Teacher",
      school_id: 1,
      province_id: 1,
      district_id: 1,
      is_active: true,
      created_at: "2024-01-02T00:00:00Z",
      updated_at: "2024-01-02T00:00:00Z",
    },
    {
      id: 3,
      full_name: "Mr. Pisach Lim",
      email: "pisach.lim@tarl.edu.kh",
      phone: "012-567-890",
      role: "teacher",
      position: "Mathematics Teacher",
      school_id: 2,
      province_id: 1,
      district_id: 2,
      is_active: true,
      created_at: "2024-01-03T00:00:00Z",
      updated_at: "2024-01-03T00:00:00Z",
    },
    {
      id: 4,
      full_name: "Ms. Sreypov Keo",
      email: "sreypov.keo@tarl.edu.kh",
      phone: "012-678-901",
      role: "collector",
      position: "Data Collector",
      school_id: 3,
      province_id: 2,
      district_id: 3,
      is_active: true,
      created_at: "2024-01-04T00:00:00Z",
      updated_at: "2024-01-04T00:00:00Z",
    },
    {
      id: 5,
      full_name: "Mr. Virak Chann",
      email: "virak.chann@tarl.edu.kh",
      phone: "012-789-012",
      role: "coordinator",
      position: "Regional Coordinator",
      school_id: null,
      province_id: 3,
      district_id: 5,
      is_active: true,
      created_at: "2024-01-05T00:00:00Z",
      updated_at: "2024-01-05T00:00:00Z",
    },
  ],

  // School data
  schools: [
    {
      id: 1,
      name: "Angkor High School",
      name_kh: "វិទ្យាល័យអង្គរ",
      code: "AHS001",
      province_id: 1,
      district_id: 1,
      address: "Siem Reap City Center, Street 6",
      contact_person: "Mr. Sopheak Mao",
      phone: "012-345-678",
      email: "angkor.hs@edu.gov.kh",
      director_name: "Dr. Channary Lim",
      total_students: 450,
      total_teachers: 25,
      is_active: true,
      created_at: "2024-01-01T00:00:00Z",
      updated_at: "2024-01-01T00:00:00Z",
    },
    {
      id: 2,
      name: "Bayon Primary School",
      name_kh: "សាលាបឋមសិក្សាបាយ័ន",
      code: "BPS001",
      province_id: 1,
      district_id: 2,
      address: "Angkor Chum District, Village 3",
      contact_person: "Ms. Channary Lim",
      phone: "012-456-789",
      email: "bayon.ps@edu.gov.kh",
      director_name: "Mr. Dara Pich",
      total_students: 320,
      total_teachers: 18,
      is_active: true,
      created_at: "2024-01-01T00:00:00Z",
      updated_at: "2024-01-01T00:00:00Z",
    },
    {
      id: 3,
      name: "Battambang Provincial School",
      name_kh: "សាលាខេត្តបាត់ដំបង",
      code: "BPS002",
      province_id: 2,
      district_id: 3,
      address: "Battambang City Center",
      contact_person: "Mr. Pisach Nhem",
      phone: "012-567-890",
      email: "bb.provincial@edu.gov.kh",
      director_name: "Ms. Bopha Nhem",
      total_students: 380,
      total_teachers: 22,
      is_active: true,
      created_at: "2024-01-01T00:00:00Z",
      updated_at: "2024-01-01T00:00:00Z",
    },
    {
      id: 4,
      name: "Chamkar Mon Primary",
      name_kh: "សាលាបឋមសិក្សាចំការមន",
      code: "CMP001",
      province_id: 3,
      district_id: 5,
      address: "Chamkar Mon, Phnom Penh",
      contact_person: "Mr. Dara Pich",
      phone: "012-789-012",
      email: "chamkarmon.ps@edu.gov.kh",
      director_name: "Ms. Maly Sok",
      total_students: 520,
      total_teachers: 28,
      is_active: true,
      created_at: "2024-01-01T00:00:00Z",
      updated_at: "2024-01-01T00:00:00Z",
    },
    {
      id: 5,
      name: "Daun Penh High School",
      name_kh: "វិទ្យាល័យដូនពេញ",
      code: "DPH001",
      province_id: 3,
      district_id: 6,
      address: "Daun Penh, Phnom Penh",
      contact_person: "Ms. Bopha Nhem",
      phone: "012-890-123",
      email: "daunpenh.hs@edu.gov.kh",
      director_name: "Dr. Sophea Chann",
      total_students: 680,
      total_teachers: 35,
      is_active: true,
      created_at: "2024-01-01T00:00:00Z",
      updated_at: "2024-01-01T00:00:00Z",
    },
  ],

  // Observation data
  observations: [
    {
      id: 1,
      school_name: "Angkor High School",
      visit_date: "2024-01-15",
      mentor_name: "Dr. Sophea Chann",
      teacher_name: "Ms. Maly Sok",
      province: "Siem Reap",
      district: "Siem Reap City",
      subject_observed: "Mathematics",
      tarl_class_taking_place: "Yes",
      total_students_present: 28,
      students_at_level: 22,
      grade_group: "Std. 3-6",
      class_started_on_time: "Yes",
      children_grouped_appropriately: "Yes",
      students_fully_involved: "Yes",
      teacher_had_session_plan: "Yes",
      created_at: "2024-01-15T10:00:00Z",
    },
    {
      id: 2,
      school_name: "Bayon Primary School",
      visit_date: "2024-01-12",
      mentor_name: "Prof. Dara Pich",
      teacher_name: "Mr. Pisach Lim",
      province: "Siem Reap",
      district: "Angkor Chum",
      subject_observed: "Khmer Language",
      tarl_class_taking_place: "Yes",
      total_students_present: 35,
      students_at_level: 28,
      grade_group: "Std. 1-2",
      class_started_on_time: "No",
      children_grouped_appropriately: "Yes",
      students_fully_involved: "Yes",
      teacher_had_session_plan: "Yes",
      created_at: "2024-01-12T09:30:00Z",
    },
    {
      id: 3,
      school_name: "Battambang Provincial School",
      visit_date: "2024-01-10",
      mentor_name: "Ms. Bopha Nhem",
      teacher_name: "Ms. Sreypov Keo",
      province: "Battambang",
      district: "Battambang City",
      subject_observed: "Mathematics",
      tarl_class_taking_place: "No",
      tarl_class_not_taking_place_reason: "Teacher is Absent",
      total_students_present: 0,
      students_at_level: 0,
      grade_group: "Std. 3-6",
      created_at: "2024-01-10T14:00:00Z",
    },
  ],

  // Training feedback data
  trainingFeedback: [
    {
      id: 1,
      training_id: "TRL001",
      training_title: "TaRL Methodology Training",
      training_date: "2024-01-15",
      trainer_name: "Dr. Sophea Chann",
      participant_name: "Ms. Maly Sok",
      participant_email: "maly.sok@tarl.edu.kh",
      respondent_type: "Teacher",
      school_id: 1,
      province_id: 1,
      district_id: 1,
      overall_rating: 5,
      content_quality_rating: 5,
      trainer_effectiveness_rating: 5,
      venue_rating: 4,
      years_of_experience: 8,
      previous_tarl_training: false,
      most_valuable_aspect: "Practical activities and hands-on learning approach",
      suggestions_for_improvement: "More time for practice sessions",
      will_recommend_training: true,
      will_apply_learning: true,
      created_at: "2024-01-15T16:00:00Z",
      updated_at: "2024-01-15T16:00:00Z",
    },
    {
      id: 2,
      training_id: "TRL002",
      training_title: "Assessment Techniques Workshop",
      training_date: "2024-01-20",
      trainer_name: "Prof. Dara Pich",
      participant_name: "Mr. Pisach Lim",
      participant_email: "pisach.lim@tarl.edu.kh",
      respondent_type: "Teacher",
      school_id: 2,
      province_id: 1,
      district_id: 2,
      overall_rating: 4,
      content_quality_rating: 4,
      trainer_effectiveness_rating: 5,
      venue_rating: 4,
      years_of_experience: 6,
      previous_tarl_training: true,
      most_valuable_aspect: "Different assessment methods and tools",
      suggestions_for_improvement: "Include more digital assessment tools",
      will_recommend_training: true,
      will_apply_learning: true,
      created_at: "2024-01-20T15:30:00Z",
      updated_at: "2024-01-20T15:30:00Z",
    },
  ],

  // Student data
  students: [
    {
      id: 1,
      name: "Sophea Chan",
      school_name: "Angkor High School",
      grade: "Grade 5",
      age: 11,
      gender: "Female",
      enrollment_date: "2024-01-15",
      status: "active",
      subjects: ["Math", "Khmer"],
      performance_level: "Above Average",
    },
    {
      id: 2,
      name: "Dara Pich",
      school_name: "Battambang Provincial School",
      grade: "Grade 4",
      age: 10,
      gender: "Male",
      enrollment_date: "2024-02-01",
      status: "active",
      subjects: ["Math", "Science"],
      performance_level: "Average",
    },
    {
      id: 3,
      name: "Maly Sok",
      school_name: "Bayon Primary School",
      grade: "Grade 3",
      age: 9,
      gender: "Female",
      enrollment_date: "2024-01-20",
      status: "active",
      subjects: ["Khmer", "Math"],
      performance_level: "Below Average",
    },
    {
      id: 4,
      name: "Pisach Lim",
      school_name: "Chamkar Mon Primary",
      grade: "Grade 6",
      age: 12,
      gender: "Male",
      enrollment_date: "2024-01-10",
      status: "active",
      subjects: ["Math", "Science", "English"],
      performance_level: "Excellent",
    },
    {
      id: 5,
      name: "Sreypov Keo",
      school_name: "Daun Penh High School",
      grade: "Grade 2",
      age: 8,
      gender: "Female",
      enrollment_date: "2024-01-25",
      status: "active",
      subjects: ["Khmer", "Math"],
      performance_level: "Good",
    },
  ],

  // Learning progress data
  learningProgress: [
    {
      id: 1,
      student_id: 1,
      student_name: "Sophea Chan",
      school_name: "Angkor High School",
      subject_code: "MATH",
      subject_name: "Mathematics",
      total_hours_studied: 45.5,
      target_hours_per_subject: 60,
      hours_progress_percentage: 75.8,
      tasks_completed: 8,
      total_tasks_assigned: 10,
      task_completion_percentage: 80,
      total_study_sessions: 15,
    },
    {
      id: 2,
      student_id: 2,
      student_name: "Dara Pich",
      school_name: "Battambang Provincial School",
      subject_code: "KHMER",
      subject_name: "Khmer Language",
      total_hours_studied: 32.0,
      target_hours_per_subject: 50,
      hours_progress_percentage: 64.0,
      tasks_completed: 6,
      total_tasks_assigned: 8,
      task_completion_percentage: 75,
      total_study_sessions: 12,
    },
  ],

  // Assessment results data
  assessmentResults: [
    {
      student_id: 1,
      student_name: "Sophea Chan",
      school_name: "Angkor High School",
      subject: "Math",
      lesson_title_en: "Addition and Subtraction",
      assessment_type: "Quiz",
      avg_percentage: 85.5,
      max_percentage: 92.0,
      min_percentage: 78.0,
      total_assessments: 3,
      latest_assessment_date: "2024-01-15",
    },
    {
      student_id: 2,
      student_name: "Dara Pich",
      school_name: "Battambang Provincial School",
      subject: "Khmer",
      lesson_title_en: "Reading Comprehension",
      assessment_type: "Assignment",
      avg_percentage: 76.0,
      max_percentage: 88.0,
      min_percentage: 65.0,
      total_assessments: 2,
      latest_assessment_date: "2024-01-12",
    },
    {
      student_id: 3,
      student_name: "Maly Sok",
      school_name: "Bayon Primary School",
      subject: "Math",
      lesson_title_en: "Multiplication",
      assessment_type: "Practical",
      avg_percentage: 92.5,
      max_percentage: 95.0,
      min_percentage: 90.0,
      total_assessments: 2,
      latest_assessment_date: "2024-01-10",
    },
  ],

  // Reports data
  reports: [
    {
      id: "1",
      title: "Monthly Observations Report",
      description: "Comprehensive report of all observations conducted this month",
      type: "observations" as const,
      generatedAt: new Date().toISOString(),
      status: "ready" as const,
      downloadUrl: "#",
    },
    {
      id: "2",
      title: "School Performance Summary",
      description: "Performance metrics and statistics for all participating schools",
      type: "schools" as const,
      generatedAt: new Date(Date.now() - 86400000).toISOString(),
      status: "ready" as const,
      downloadUrl: "#",
    },
    {
      id: "3",
      title: "User Activity Report",
      description: "User engagement and activity statistics",
      type: "users" as const,
      generatedAt: new Date(Date.now() - 172800000).toISOString(),
      status: "generating" as const,
    },
    {
      id: "4",
      title: "Training Effectiveness Report",
      description: "Analysis of training feedback and effectiveness metrics",
      type: "training" as const,
      generatedAt: new Date(Date.now() - 259200000).toISOString(),
      status: "ready" as const,
      downloadUrl: "#",
    },
  ],
}

// Helper functions to simulate API calls
export const MockDataService = {
  async getUsers() {
    await new Promise((resolve) => setTimeout(resolve, 500)) // Simulate API delay
    return mockData.users
  },

  async getSchools() {
    await new Promise((resolve) => setTimeout(resolve, 500))
    return mockData.schools
  },

  async getObservations() {
    await new Promise((resolve) => setTimeout(resolve, 500))
    return mockData.observations
  },

  async getTrainingFeedback() {
    await new Promise((resolve) => setTimeout(resolve, 500))
    return mockData.trainingFeedback
  },

  async getStudents() {
    await new Promise((resolve) => setTimeout(resolve, 500))
    return mockData.students
  },

  async getLearningProgress() {
    await new Promise((resolve) => setTimeout(resolve, 500))
    return mockData.learningProgress
  },

  async getAssessmentResults() {
    await new Promise((resolve) => setTimeout(resolve, 500))
    return mockData.assessmentResults
  },

  async getReports() {
    await new Promise((resolve) => setTimeout(resolve, 500))
    return mockData.reports
  },
}
